communication:
  bandwidth_download: 100Mbit
  bandwidth_upload: 100Mbit
  latency: 50ms
  limit_network_resource: false
  method: SocketIO
  port: 8000
docker:
  enable_gpu: false
  image: fedeval:v1
  num_containers: 2
  num_gpu: 0
log:
  base_level: INFO
  console_log_level: INFO
  file_log_level: INFO
  log_dir: log/implementation
server:
  host: server
  listen: server
  num_clients: 2
  port: 8000
  secret_key: secret!
