clients:
  bandwidth: 100Mbit
  local_batch_size: 32
  local_rounds: 2
  lr: '0.0005'
  num_clients: 100
  script: client.py
docker:
  image: fleval:v1
machines:
  m1:
    capacity: 30
    dir: /home/ubuntu/FML
    host: 192.168.0.0
    key: key_file
    port: 22
    user_name: ubuntu
  m2:
    capacity: 30
    dir: /home/ubuntu/FML
    host: 192.168.0.1
    key: key_file
    port: 22
    user_name: ubuntu
  m3:
    capacity: 40
    dir: /home/ubuntu/FML
    host: 192.168.0.2
    key: key_file
    port: 22
    user_name: ubuntu
  server:
    dir: /home/ubuntu/FML
    host: 192.168.0.2
    key: key_file
    port: 22
    user_name: ubuntu
server:
  MAX_NUM_ROUNDS: 2000
  MIN_NUM_WORKERS: 100
  NUM_CLIENTS_CONTACTED_PER_ROUND: 10
  NUM_TOLERATE: 20
  ROUNDS_BETWEEN_TEST: 1
  ROUNDS_BETWEEN_VALIDATIONS: 1
  host: 192.168.0.2
  listen: 0.0.0.0
  port: 8200
  save_gradients: false
  script: server.py
