networks:
  server-clients:
    driver: bridge
services:
  container_0:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CONTAINER_ID=0 && python3 -W ignore -m FedEval.run -f run
      -r client -c configs/FedSVD_tmp"
    container_name: container0
    depends_on:
    - server
    environment:
    - UNIFIED_JOB_ID=2022_0127_110159
    - NVIDIA_VISIBLE_DEVICES=-1
    image: fedeval:v1
    networks:
    - server-clients
    volumes:
    - /mnt/d/Nutstore/FedEval/FedEval-Code-WithData:/FML
    working_dir: /FML
  container_1:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CONTAINER_ID=1 && python3 -W ignore -m FedEval.run -f run
      -r client -c configs/FedSVD_tmp"
    container_name: container1
    depends_on:
    - server
    environment:
    - UNIFIED_JOB_ID=2022_0127_110159
    - NVIDIA_VISIBLE_DEVICES=-1
    image: fedeval:v1
    networks:
    - server-clients
    volumes:
    - /mnt/d/Nutstore/FedEval/FedEval-Code-WithData:/FML
    working_dir: /FML
  server:
    cap_add:
    - NET_ADMIN
    command: sh -c "python3 -W ignore -m FedEval.run -f run -r server -c configs/FedSVD_tmp"
    container_name: server
    environment:
    - UNIFIED_JOB_ID=2022_0127_110159
    image: fedeval:v1
    networks:
    - server-clients
    ports:
    - 8000:8000
    volumes:
    - /mnt/d/Nutstore/FedEval/FedEval-Code-WithData:/FML
    working_dir: /FML
version: '2'
