networks:
  server-clients:
    driver: bridge
services:
  client_0:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=0 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client0
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_1:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=1 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client1
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_2:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=2 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client2
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_3:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=3 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client3
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_4:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=4 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client4
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_5:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=5 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client5
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_6:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=6 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client6
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_7:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=7 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client7
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_8:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=8 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client8
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  client_9:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CLIENT_ID=9 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 client.py --path ./"
    container_name: client9
    image: fleval:v1
    networks:
    - server-clients
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
  server:
    cap_add:
    - NET_ADMIN
    command: sh -c "python3 server.py --path ./"
    container_name: server
    image: fleval:v1
    networks:
    - server-clients
    ports:
    - 8200:8200
    volumes:
    - D:\FML-Master:/FML
    working_dir: /FML
version: '2'
