networks:
  server-clients:
    driver: bridge
services:
  container_0:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CONTAINER_ID=0 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 -W ignore -m FedEval.run -f run -r client
      -c configs/quickstart"
    container_name: container0
    image: fedeval:v1
    networks:
    - server-clients
    volumes:
    - /Users/derek/Documents/Nutstore/FedEval/FedEval-Code-WithData:/FML
    working_dir: /FML
  container_1:
    cap_add:
    - NET_ADMIN
    command: sh -c "export CONTAINER_ID=1 && tc qdisc add dev eth0 root tbf rate 100Mbit
      latency 50ms burst 15kb && python3 -W ignore -m FedEval.run -f run -r client
      -c configs/quickstart"
    container_name: container1
    image: fedeval:v1
    networks:
    - server-clients
    volumes:
    - /Users/derek/Documents/Nutstore/FedEval/FedEval-Code-WithData:/FML
    working_dir: /FML
  server:
    cap_add:
    - NET_ADMIN
    command: sh -c "python3 -W ignore -m FedEval.run -f run -r server -c configs/quickstart"
    container_name: server
    image: fedeval:v1
    networks:
    - server-clients
    ports:
    - 8080:8080
    volumes:
    - /Users/derek/Documents/Nutstore/FedEval/FedEval-Code-WithData:/FML
    working_dir: /FML
version: '2'
