FedModel:
  B: 8
  C: 0.1
  E: 10
  beta1: 0.9
  beta2: 0.99
  eta: 1.0
  max_rounds: 3000
  mu: 0.01
  name: FedAvg
  num_tolerance: 500
  opt_name: fedyogi
  rounds_between_val: 1
  sparsity: 0.01
  tau: 0.0001
MLModel:
  activation: relu
  dropout: 0.2
  loss: categorical_crossentropy
  metrics:
  - accuracy
  name: LeNet
  optimizer:
    lr: 0.001
    momentum: 0
    name: sgd
  units:
  - 512
  - 512
