FedModel:
  B: 1000
  C: 1.0
  E: 1
  beta1: 0.9
  beta2: 0.99
  eta: 1.0
  max_rounds: 10000
  mu: 0.01
  name: FedSTC
  num_tolerance: 500
  opt_name: fedyogi
  rounds_between_val: 1
  sparsity: 0.1
  tau: 0.0001
MLModel:
  activation: relu
  dropout: 0.2
  embedding_dim: 0
  hidden_units: 64
  loss: binary_crossentropy
  metrics:
  - binary_accuracy
  name: StackedLSTM
  optimizer:
    lr: 0.05
    momentum: 0
    name: sgd
  units:
  - 512
  - 512
