# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='comm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncomm.proto\x1a\x1bgoogle/protobuf/empty.proto\"[\n\x0eRoundModelInfo\x12\x14\n\x0cround_number\x18\x01 \x01(\x03\x12\x19\n\x11weights_file_name\x18\x02 \x01(\t\x12\x18\n\x10selected_clients\x18\x03 \x03(\x03\"\xdb\x01\n\x0cUpdateResult\x12\x0b\n\x03\x63id\x18\x01 \x01(\x03\x12\x14\n\x0cround_number\x18\x02 \x01(\x03\x12\x1a\n\x12local_round_number\x18\x03 \x01(\x03\x12\x0f\n\x07weights\x18\x04 \x01(\t\x12\x12\n\ntrain_size\x18\x05 \x01(\x03\x12\x12\n\ntrain_loss\x18\x06 \x01(\x01\x12\x1c\n\x14time_receive_request\x18\x07 \x01(\x02\x12\x19\n\x11time_start_update\x18\x08 \x01(\x02\x12\x1a\n\x12time_finish_update\x18\t \x01(\x02\"\xbc\x01\n\x10\x45valuationResult\x12\x0b\n\x03\x63id\x18\x01 \x01(\x03\x12\x14\n\x0cround_number\x18\x02 \x01(\x03\x12\x1a\n\x12local_round_number\x18\x03 \x01(\x03\x12\x1c\n\x14time_receive_request\x18\x04 \x01(\x02\x12\x1b\n\x13time_start_evaluate\x18\x05 \x01(\x02\x12\x1c\n\x14time_finish_evaluate\x18\x06 \x01(\x02\x12\x10\n\x08\x65valuate\x18\x07 \x01(\t\"8\n\x0cRegistration\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\x03\x12\x12\n\nclient_ids\x18\x02 \x03(\x03\"\x80\x02\n\x0fProtocolMessage\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12%\n\x0cregistration\x18\x02 \x01(\x0b\x32\r.RegistrationH\x00\x12+\n\x10round_model_info\x18\x03 \x01(\x0b\x32\x0f.RoundModelInfoH\x00\x12&\n\rupdate_result\x18\x04 \x01(\x0b\x32\r.UpdateResultH\x00\x12.\n\x11\x65valuation_result\x18\x05 \x01(\x0b\x32\x11.EvaluationResultH\x00\x12\'\n\x05\x65mpty\x18\x06 \x01(\x0b\x32\x16.google.protobuf.EmptyH\x00\x42\t\n\x07payload2H\n\x11\x46\x65\x64\x65ratedLearning\x12\x33\n\x07\x63onnect\x12\x10.ProtocolMessage\x1a\x10.ProtocolMessage\"\x00(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ROUNDMODELINFO = _descriptor.Descriptor(
  name='RoundModelInfo',
  full_name='RoundModelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='round_number', full_name='RoundModelInfo.round_number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights_file_name', full_name='RoundModelInfo.weights_file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selected_clients', full_name='RoundModelInfo.selected_clients', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=134,
)


_UPDATERESULT = _descriptor.Descriptor(
  name='UpdateResult',
  full_name='UpdateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='UpdateResult.cid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round_number', full_name='UpdateResult.round_number', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_round_number', full_name='UpdateResult.local_round_number', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weights', full_name='UpdateResult.weights', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_size', full_name='UpdateResult.train_size', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_loss', full_name='UpdateResult.train_loss', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_receive_request', full_name='UpdateResult.time_receive_request', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_start_update', full_name='UpdateResult.time_start_update', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_finish_update', full_name='UpdateResult.time_finish_update', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=356,
)


_EVALUATIONRESULT = _descriptor.Descriptor(
  name='EvaluationResult',
  full_name='EvaluationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='EvaluationResult.cid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round_number', full_name='EvaluationResult.round_number', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_round_number', full_name='EvaluationResult.local_round_number', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_receive_request', full_name='EvaluationResult.time_receive_request', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_start_evaluate', full_name='EvaluationResult.time_start_evaluate', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_finish_evaluate', full_name='EvaluationResult.time_finish_evaluate', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evaluate', full_name='EvaluationResult.evaluate', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=547,
)


_REGISTRATION = _descriptor.Descriptor(
  name='Registration',
  full_name='Registration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_id', full_name='Registration.container_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_ids', full_name='Registration.client_ids', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=549,
  serialized_end=605,
)


_PROTOCOLMESSAGE = _descriptor.Descriptor(
  name='ProtocolMessage',
  full_name='ProtocolMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='ProtocolMessage.event', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='registration', full_name='ProtocolMessage.registration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round_model_info', full_name='ProtocolMessage.round_model_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_result', full_name='ProtocolMessage.update_result', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='evaluation_result', full_name='ProtocolMessage.evaluation_result', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='empty', full_name='ProtocolMessage.empty', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='ProtocolMessage.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=608,
  serialized_end=864,
)

_PROTOCOLMESSAGE.fields_by_name['registration'].message_type = _REGISTRATION
_PROTOCOLMESSAGE.fields_by_name['round_model_info'].message_type = _ROUNDMODELINFO
_PROTOCOLMESSAGE.fields_by_name['update_result'].message_type = _UPDATERESULT
_PROTOCOLMESSAGE.fields_by_name['evaluation_result'].message_type = _EVALUATIONRESULT
_PROTOCOLMESSAGE.fields_by_name['empty'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
_PROTOCOLMESSAGE.oneofs_by_name['payload'].fields.append(
  _PROTOCOLMESSAGE.fields_by_name['registration'])
_PROTOCOLMESSAGE.fields_by_name['registration'].containing_oneof = _PROTOCOLMESSAGE.oneofs_by_name['payload']
_PROTOCOLMESSAGE.oneofs_by_name['payload'].fields.append(
  _PROTOCOLMESSAGE.fields_by_name['round_model_info'])
_PROTOCOLMESSAGE.fields_by_name['round_model_info'].containing_oneof = _PROTOCOLMESSAGE.oneofs_by_name['payload']
_PROTOCOLMESSAGE.oneofs_by_name['payload'].fields.append(
  _PROTOCOLMESSAGE.fields_by_name['update_result'])
_PROTOCOLMESSAGE.fields_by_name['update_result'].containing_oneof = _PROTOCOLMESSAGE.oneofs_by_name['payload']
_PROTOCOLMESSAGE.oneofs_by_name['payload'].fields.append(
  _PROTOCOLMESSAGE.fields_by_name['evaluation_result'])
_PROTOCOLMESSAGE.fields_by_name['evaluation_result'].containing_oneof = _PROTOCOLMESSAGE.oneofs_by_name['payload']
_PROTOCOLMESSAGE.oneofs_by_name['payload'].fields.append(
  _PROTOCOLMESSAGE.fields_by_name['empty'])
_PROTOCOLMESSAGE.fields_by_name['empty'].containing_oneof = _PROTOCOLMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['RoundModelInfo'] = _ROUNDMODELINFO
DESCRIPTOR.message_types_by_name['UpdateResult'] = _UPDATERESULT
DESCRIPTOR.message_types_by_name['EvaluationResult'] = _EVALUATIONRESULT
DESCRIPTOR.message_types_by_name['Registration'] = _REGISTRATION
DESCRIPTOR.message_types_by_name['ProtocolMessage'] = _PROTOCOLMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoundModelInfo = _reflection.GeneratedProtocolMessageType('RoundModelInfo', (_message.Message,), {
  'DESCRIPTOR' : _ROUNDMODELINFO,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:RoundModelInfo)
  })
_sym_db.RegisterMessage(RoundModelInfo)

UpdateResult = _reflection.GeneratedProtocolMessageType('UpdateResult', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESULT,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:UpdateResult)
  })
_sym_db.RegisterMessage(UpdateResult)

EvaluationResult = _reflection.GeneratedProtocolMessageType('EvaluationResult', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONRESULT,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:EvaluationResult)
  })
_sym_db.RegisterMessage(EvaluationResult)

Registration = _reflection.GeneratedProtocolMessageType('Registration', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATION,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:Registration)
  })
_sym_db.RegisterMessage(Registration)

ProtocolMessage = _reflection.GeneratedProtocolMessageType('ProtocolMessage', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLMESSAGE,
  '__module__' : 'comm_pb2'
  # @@protoc_insertion_point(class_scope:ProtocolMessage)
  })
_sym_db.RegisterMessage(ProtocolMessage)



_FEDERATEDLEARNING = _descriptor.ServiceDescriptor(
  name='FederatedLearning',
  full_name='FederatedLearning',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=866,
  serialized_end=938,
  methods=[
  _descriptor.MethodDescriptor(
    name='connect',
    full_name='FederatedLearning.connect',
    index=0,
    containing_service=None,
    input_type=_PROTOCOLMESSAGE,
    output_type=_PROTOCOLMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEDERATEDLEARNING)

DESCRIPTOR.services_by_name['FederatedLearning'] = _FEDERATEDLEARNING

# @@protoc_insertion_point(module_scope)
