data_dir: data
dataset: femnist
non-iid: False
non-iid-class: 1 # Only work when non-iid = True
non-iid-strategy: average # Only work when non-iid = True
normalize: true
sample_size: 100000000
shared_data: 0
train_val_test:
  - 0.8
  - 0.1
  - 0.1
