clients:
  bandwidth: 100Mbit
docker:
  image: fedeval:gpu
  num_containers: 100
  enable_gpu: False
  num_gpu: 0
server:
  host: server
  listen: server
  num_clients: 100
  port: 8000
  secret_key: secret!
log:
  log_dir: log/local
  base_level: INFO
  file_log_level: INFO
  console_log_level: ERROR
communication:
  method: SocketIO
  port: 8000