clients:
  bandwidth: 100Mbit
docker:
  image: fedeval:gpu
  num_containers: 40
  enable_gpu: True
  num_gpu: 8
server:
  host: server
  listen: server
  num_clients: 100
  port: 8000
  secret: secret!
log_dir: log/local