clients:
  bandwidth: 100Mbit
docker:
  image: fedeval:gpu
  num_containers: 40
  enable_gpu: True
  num_gpu: 8
server:
  host: server
  listen: server
  num_clients: 100
  port: 8000
  secret_key: secret!
log:
  log_dir: log/local
  base_level: INFO
  file_log_level: INFO
  console_log_level: ERROR