FedModel:
  name: FedSGD
  train_strategy:
    B: 1000
    C: 1.0
    E: 1
    lazy_update: true
    max_num_rounds: 1000
    num_tolerance: 20
    rounds_between_val: 1
  upload_strategy:
    upload_dismiss: []
    upload_optimizer: true
    upload_sparsity: 0.01
MLModel:
  LeNet:
    activation: relu
    lr: 0.0005
    optimizer: adam
    pooling: max
  MLP:
    activation: relu
    dropout: 0.2
    lr: 0.0005
    optimizer: gd
    units:
    - 512
    - 512
  lr: 0.0005
  name: LeNet
  optimizer: sgd
name: LeNet
