docker:
  image: fedeval:gpu
  num_containers: 10
  enable_gpu: False
  num_gpu: 0
server:
  host: server
  listen: server
  num_clients: 10
  port: 8000
  secret_key: secret!
log:
  log_dir: log/quickstart
  base_level: INFO
  file_log_level: INFO
  console_log_level: ERROR
communication:
  method: SocketIO
  port: 8000
  limit_network_resource: True
  bandwidth_upload: 10Mbit
  bandwidth_download: 30Mbit
  latency: 50ms