docker:
  image: fedeval:v1
  num_containers: 1
  enable_gpu: true
  num_gpu: 1
server:
  host: 127.0.0.1
  listen: 127.0.0.1
  num_clients: 1000
  port: 8001
  secret_key: secret!
log:
  log_dir: log/quickstart
  base_level: INFO
  file_log_level: INFO
  console_log_level: INFO
communication:
  method: SocketIO
  port: 8001
  limit_network_resource: false
  bandwidth_upload: 10Mbit
  bandwidth_download: 30Mbit
  latency: 50ms
  fast_mode: true