data_dir: data
dataset: synthetic_matrix_vertical
non-iid: False
non-iid-class: 0 # Only work when non-iid = True
non-iid-strategy: natural # Only work when non-iid = True
normalize: true
sample_size: 1000 # per client
synthetic_features: 1000
train_val_test:
  - 1.0
  - 0
  - 0