clients:
  bandwidth: 100Mbit
docker:
  image: fedeval:v1
  num_containers: 100
server:
  host: 10.173.1.22
  listen: 0.0.0.0
  num_clients: 100
  port: 8000
  secret_key: secret!
machines:
  server:
    host: 10.173.1.22
    port: 22
    user_name: ubuntu
    dir: /ldisk/chaidi/FedEval
    key: id_rsa
  m1:
    host: 10.173.1.22
    port: 22
    capacity: 100
    user_name: ubuntu
    dir: /ldisk/chaidi/FedEval
    key: id_rsa
log_dir: log/workstation