docker:
  image: fedeval:v1
  num_containers: 10
server:
  host: 10.173.1.22
  listen: 0.0.0.0
  num_clients: 10
  port: 8000
  secret_key: secret!
machines:
  server:
    host: 10.173.1.22
    port: 22
    username: ubuntu
    dir: /ldisk/chaidi/FedEval/FedEval-Code-WithData
    key: id_rsa
  m1:
    host: 10.173.1.22
    port: 22
    capacity: 100
    username: ubuntu
    dir: /ldisk/chaidi/FedEval/FedEval-Code-WithData
    key: id_rsa
log:
  log_dir: log/workstation
  base_level: INFO
  file_log_level: INFO
  console_log_level: ERROR
communication:
  method: SocketIO
  port: 8000
  limit_network_resource: True
  bandwidth_upload: 10Mbit
  bandwidth_download: 30Mbit
  latency: 50ms