data_dir: data
dataset: synthetic_matrix_horizontal_memmap
feature_size: 932
non-iid: false
non-iid-class: 0
non-iid-strategy: natural
normalize: false
random_seed: 100
sample_size: 1922
train_val_test:
- 1.0
- 0
- 0
