data_dir: data
dataset: celeba
non-iid: True
non-iid-class: 0 # Only work when non-iid = True
non-iid-strategy: natural # Only work when non-iid = True
normalize: true
sample_size: 300
train_val_test:
  - 0.8
  - 0.1
  - 0.1
