docker:
  image: fedeval:v1
  num_containers: 100
  enable_gpu: False
  num_gpu: 0
server:
  host: server
  listen: server
  num_clients: 5304
  port: 8000
  secret_key: secret!
log:
  log_dir: log/debug
  base_level: INFO
  file_log_level: INFO
  console_log_level: ERROR
communication:
  method: SocketIO
  port: 8000
  limit_network_resource: False
  bandwidth_upload: 10Mbit
  bandwidth_download: 30Mbit
  latency: 50ms