communication:
  bandwidth_download: 100Mbit
  bandwidth_upload: 100Mbit
  latency: 50ms
  limit_network_resource: false
  method: SocketIO
  port: 8080
docker:
  enable_gpu: true
  image: fedeval:v1
  num_containers: 8
  num_gpu: 0
log:
  base_level: INFO
  console_log_level: INFO
  file_log_level: INFO
  log_dir: log/debug0406
server:
  host: server
  listen: server
  num_clients: 3500
  port: 8080
  secret_key: secret!
