data_dir: data
dataset: mnist_matrix
feature_size: 100000
non-iid: false
non-iid-class: 0
non-iid-strategy: natural
normalize: false
random_seed: 100
sample_size: 100000
train_val_test:
- 1.0
- 0
- 0
