data_dir: data
dataset: mnist_matrix
non-iid: False
non-iid-class: 0 # Only work when non-iid = True
non-iid-strategy: natural # Only work when non-iid = True
normalize: true
sample_size: 10000 # per client
train_val_test:
  - 1.0
  - 0
  - 0
