FedModel:
  B: 8
  C: 1.0
  E: 1
  block_size: 1000
  distributed_evaluate: true
  fedsvd_debug_evaluate: false
  fedsvd_lr_l2: 0
  fedsvd_mode: lr
  fedsvd_opt_1: true
  fedsvd_opt_2: true
  fedsvd_top_k: -1
  max_rounds: 10000
  name: FedSVD
  num_tolerance: 300
  rounds_between_val: 1
MLModel: null
