FedModel:
  B: 8
  C: 1.0
  E: 1
  block_size: '1000'
  fedsvd_lr_l2: '0'
  fedsvd_mode: lr
  fedsvd_top_k: '-1'
  max_rounds: 10000
  name: FedSVD
  num_tolerance: 300
  fedsvd_opt_1: True
  fedsvd_opt_2: True
  fedsvd_debug_evaluate: True
MLModel:
  activation: relu
  dropout: 0.2
  loss: categorical_crossentropy
  metrics:
  - accuracy
  name: LeNet
  optimizer:
    lr: 0.1
    momentum: 0.9
    name: sgd
  units:
  - 512
  - 512
