name: unittest

on:
  push:
    branches: [ restruture ]
  pull_request:
    branches: [ restruture ]

  workflow_dispatch:
    branches: [ restruture ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./docker/requirements-unittest.txt
    - name: Unittest
      run: |
        python -m unittest
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v2